const QUESTION_ACTION_TYPE = {
  DATA_RECEIVED: "DATA_RECEIVED",
  DATA_FAILED: "DATA_FAILED",
  ACTIVE: "ACTIVE",
  NEW_ANSWER: "NEW_ANSWER",
  NEXT_QUESTION: "NEXT_QUESTION",
  FINISHED: "FINISHED",
  RESTART: "RESTART",
};

export default QUESTION_ACTION_TYPE;
